imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [SymfonyCmfSimpleCmsBundle, SymfonyCmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

        #lessphp:
            #file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            #apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - en
                - es
                - ca
            es:
                - es
                - en
                - ca
            ca:
                - ca
                - en
                - es

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

symfony_cmf_routing_extra:
    dynamic:
        enabled: true
    use_sonata_admin: false

symfony_cmf_content:
    use_sonata_admin: false

#symfony_cmf_simple_cms:
#    routing:
#        templates_by_class:
#            Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page:  SymfonyCmfSimpleCmsBundle:Page:index.html.twig
#        controllers_by_class:
#            Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:  symfony_cmf_routing_extra.redirect_controller:redirectAction
#    multilang:
#        locales: %locales%
#    use_sonata_admin: false

ipanema_cms:
    routing:
        templates_by_class:
            Ipanema\CmsBundle\Document\Page:  IpanemaCmsBundle:Page:index.html.twig
#        controllers_by_class:
#            Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:  symfony_cmf_routing_extra.redirect_controller:redirectAction
    multilang:
        locales: %locales%
    use_sonata_admin: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts:   [admin]

sonata_admin:
    templates:
        # default global templates
        ajax:    SonataAdminBundle::ajax_layout.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }

knp_menu:
    twig: true

symfony_cmf_menu:
    menu_basepath: /cms
    use_sonata_admin: true

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\PHPCR\Odm\Document\Generic:
            valid_children:
                - all
        Ipanema\CmsBundle\Document\Page: ~
        Ipanema\CmsBundle\Document\MultilangPage: ~

symfony_cmf_create:
    phpcr_odm: true
    image:
        model_class: Symfony\Cmf\Bundle\CreateBundle\Document\Image
        controller_class: Symfony\Cmf\Bundle\CreateBundle\Controller\PHPCRImageController
        static_basepath: '/cms/simple'

lunetics_locale:
    strict_mode: true
    guessing_order:
        - cookie
        - router
        - browser
    allowed_locales: %locales%

liip_search:
    restrict_by_language: true;

symfony_cmf_search:
    document_manager_name:  default
    translation_strategy: child
    search_path: '/cms/simple'
    search_fields:
        title: title
        summary: body

fos_js_routing:
    routes_to_expose:
        - admin_ipanema_cms_multilangpage_edit
        - admin_ipanema_cms_multilangpage_create
        - admin_ipanema_cms_multilangpage_delete
        - symfony_cmf_tree_browser.phpcr_children
        - symfony_cmf_tree_browser.phpcr_move
        - sonata.admin.doctrine_phpcr.phpcrodm_children
        - sonata.admin.doctrine_phpcr.phpcrodm_move
