# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

ipanema_cms_add:
    pattern: /add-page/{path}
    defaults: { _controller: IpanemaCmsBundle:Default:addPage }
    requirements:
        path: .+

ipanema_cms_add_multilingual:
    pattern: /add-multilingual-page/{path}
    defaults: { _controller: IpanemaCmsBundle:Default:addMultilingualPage }
    requirements:
        path: .+

ipanema_cms_remove:
    pattern: /remove-page/{path}
    defaults: { _controller: IpanemaCmsBundle:Default:removePage }
    requirements:
        path: .+

home_redirect:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: /cms/simple
        permanent: true # this for 301

static:
    pattern: /{_locale}/static
    defaults:
        _controller: AcmeMainBundle:Demo:static
    requirements:
        _locale: en|de

cmf_create_rest:
    resource: "@SymfonyCmfCreateBundle/Resources/config/routing/rest.xml"

cmf_create_image:
    resource: "@SymfonyCmfCreateBundle/Resources/config/routing/image.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml

symfony_cmf_tree:
    resource: .
    type: 'symfony_cmf_tree'
